### ISSUE TITLE
Use an allegro_flare namespace

### ISSUE THREAD

**Issue by aviallon** [allegroflare/allegro_flare#152]
Using a namespace is almost mandatory for such a big project. It is especially true for this one, where the `Screen` and `Display` class collides with the ones defined in X11 or OpenGL, and thus it creates quite the mess when I try to build.

**Comment by MarkOates** [comment]
💯 A namespace is definitely needed.  I'm glad you mentioned that.  There's a few conflicts to work out (which are being addressed partially with the overhauls of the folder structure from (https://github.com/allegroflare/allegro_flare/pull/153)) and the new fixed naming structure for `AllegroFlare`.

Main steps will likely be:

1) first, the inclusion of a `allegro_flare` namespace for the [`allegro_flare/` version](https://github.com/allegroflare/allegro_flare/tree/master/include/allegro_flare) of the folder tree, with a lot of temporary `using namespace allegro_flare`s just to keep the number of simultaneous changes down.  A preference is definitely to avoid `using namespace` in the end.

2) second, the inclusion of a `AllegroFlare` namespace for the [`AllegroFlare/` version](https://github.com/allegroflare/allegro_flare/tree/master/include/AllegroFlare) of the folder tree, with similar temporary usages of `using namespace AllegroFlare` just to keep the simultaneous changes down.

After that, that namespacing should be enough to keep development easier for everybody as consolidation and depreciation of the `allegro_flare` version is resolved into the final `AllegroFlare::` version/namespace.

**Comment by MarkOates** [comment]
Alright!

We're all namespaced up. 🙂 @aviallon It should now be much easier to manage AllegroFlare with other libraries now that #156, #157, and #158 are merged.

Also, you should feel free to safely clone the latest version and not worry about any major breaking repo changes from here on.  All the major renovations are done.  This includes adding the initial `AllegroFlare/` files, flattening the folder structure, and adding namespacing. (I think there are some test updates remaining, though now that I think about it. 🤔)

The _only_ exception to the namespacing done for this issue, was the placement of some of the `ALLEGRO_COLOR` operator overloads in the global space.  This may eventually get moved back into their namespaces, but for now that particular modification involved some less-than-trivial changes so I just kept them global.

**Comment by aviallon** [comment]
no pb. It should be pretty safe to use now. I can now go straight into business :grinning:
