### ISSUE TITLE
Restore Portability in Master

### ISSUE THREAD

**Issue by MarkOates** [allegroflare/allegro_flare#176]
Recently, the project was coupled to the [`union`](https://github.com/MarkOates/union)/[`blast`](https://github.com/MarkOates/blast) build system. This was done to improve development lockstep with other projects that develop simultaneously with `allegro_flare` (and because this particular repo is not experiencing a lot of traffic/usage during that time).

To make `allegro_flare` more approachable and easier to use, the build coupling should be removed and an alternative build system should be introduced that allows this project to float independent of the other projects.

cc @aviallon because of your advocacy for CMake.

Related issue: https://github.com/allegroflare/allegro_flare/issues/174

**Comment by MarkOates** [comment]
I'm closing this for being stale. For the most part, `allegro_flare` development is coupled with the `blast` build system (`union` has been removed and is now integrated in `blast`).

The `blast` build system has been aligned and is now used internally across all projects. It's wonderful to use, and there currently isn't a plan to change that.

It's unclear what benefit would be made by switching from `make` to `CMake`.

**Comment by aviallon** [comment]
@MarkOates if you want to test other build systems, another good candidate is `meson`.
It looks good enough that some big projects are switching to it.
