### ISSUE TITLE
Make a website

### ISSUE THREAD

**Issue by MarkOates** [allegroflare/allegro_flare#86]

**Comment by MarkOates** [comment]
considering domains:

- [ ] `www.allegroflare.org`
- [ ] `www.allegroplanet.com`

**Comment by sukhchainn** [comment]
I can do that but I use python with django. Will that suffice?

**Comment by sukhchainn** [comment]
Sorry, I'm not a front end guy.
I was hoping to help with Django, but I'm working on a project alone and
because of that I'm learning front end. When I'm done then I may be able to
help you out.

**Comment by aviallon** [comment]
@MarkOates what about a GitHub Page instead ? It should largely suffice.

**Comment by MarkOates** [comment]
@aviallon That's a fantastic idea.

I looked into it, and I ended up creating a [GitHub organization](https://github.com/allegroflare), and on it created the GitHub page https://allegroflare.github.io with the repo (https://github.com/allegroflare/allegroflare.github.io).

I had to create the organization first, because the subdomain of the GitHub page has to match the username or organization name (otherwise it would have been MarkOates.github.io and that would have been annoying).

That's fantastic.  As far as what's on the actual site so far, it's not much, but it's honest work. ;)

**Comment by MarkOates** [comment]
Some updates on this.

I bought the domain `www.allegroflare.org` and it's now coordinated with GitHub pages to show it's hosting of the https://github.com/allegroflare/allegroflare.github.io repo.

Also, I've moved the `allegro_flare` repository into the `allegroflare` organization.  @aviallon You may need to update your remote with something like:

```
git remote set-url origin git@github.com:allegroflare/allegro_flare.git
```

The repository will redirect anyway, but GitHub recommends updating it [to avoid confusion](https://help.github.com/en/articles/transferring-a-repository).

**Comment by aviallon** [comment]
Thanks :+1: 
Will look into it as soon as I have time :)
If you wanna now, I'm preparing Raytraced Global Illumination for AllegroFlare :D 
That'll be nice :)

**Comment by MarkOates** [comment]
I'm closing this now.  The infrastructure for the website has been decided.

We'll be using:

- GitHub pages
- Sourced form the repo https://github.com/allegroflare/allegroflare.github.io
- The domain www.allegroflare.org is now owned and attached to it
- Will essentially be a location for basic tutorials and class reference
- More elaborate functionality (search, etc) can be explored in the future
- Actual documentation, pages, and tutorials are still to be written (That can be handled in a separate issue)

Thanks everybody!
