### ISSUE TITLE
Create a Math class

### ISSUE THREAD

**Issue by MarkOates** [allegroflare/allegro_flare#98]
However, a lot of geometry can go into `vec2d` and might not leave much left for a `Math` class.

**Comment by arvidsson** [comment]
Maybe useful constants and general stuff like clamp and whatnot?

**Comment by MarkOates** [comment]
Exactly.  Right now there are a bunch of things stuffed in [useful.h](https://github.com/MarkOates/allegro_flare/blob/master/include/allegro_flare/useful.h)/[useful.cpp](https://github.com/MarkOates/allegro_flare/blob/master/source/useful.cpp) that should belong in a `Math` class.

There are a few constants already like
- `TAU`
- `FULL_ROTATION`

And a few functions like
- `degrees_to_radians(deg)`
- `radians_to_degrees(rad)`
- `limit<T>(min, max, val)`
- `in_range<T>(min, max, val)`

Eventually, I'll need to assemble a comprehensive list practical for games.

**Comment by MarkOates** [comment]
Pushing this to `0.9`
